### PR TITLE
Get active challenge

### PR DESCRIPTION
**Pull request by iPhatty**
Relates #29 & #32

### CODE REVIEW

**Review by i2xzy — APPROVED** [review]
:floppy_disk:

**Review by haydnba — CHANGES_REQUESTED** [review]
please just tidy up the naming between files and functions - sql query should be 'getActiveChallenge'

**Review by haydnba — APPROVED** [review]
Lovely queries... 🐘

**Review by n1c0z — APPROVED** [review]
:two_men_holding_hands:  :1st_place_medal:

**Pull request merged**
