### PR TITLE
Reports

### PR DESCRIPTION
**Pull request by haydnba**
Seeking your opinions on this implementation of the report story:

- reports only available for challenges at moment.
- the merge conflicts are due to my having to rename a few parameters, can be sorted out easily
- the referrer functionality (so that user can go back to where they came from within the app - not using browser buttons) is pretty ugly and utilises query strings where it could perhaps use body parameters - will happily refactor
- there seem to be a number of edits pushed by me which I assumed were already merged to master on Friday... Any ideas??
🎃

### CODE REVIEW

**Comment by haydnba** [comment]
Will sort out route test for post report tomorrow to get codecov back up! 🤓

**Comment by haydnba** [comment]
Added tests for report post and report edge cases (get and post) - 100% codecov for `report.js` (thanks to Phat's callback) - also, I modularised the Phat cookie callback so we can require it in tests from a `utils` directory

**Comment by iPhatty** [comment]
Real nice to see that you have been playing with the app after the sprint, pretty late right now but I will deffo look through what you have done thoroughly! So far I like what I see. 👍

**Review by i2xzy — APPROVED** [review]

**Review by iPhatty — APPROVED** [review]

**Review by n1c0z — APPROVED** [review]

**Comment by haydnba** [comment]
Thanks well-beans - will resolve conflicts and merge this weekend!

**Comment by haydnba** [comment]
I feel like it's time to close this PR. I've missed you Beans! Hope things are good 💋

**Pull request closed without merging**
